### ISSUE TITLE
MoloVov 1.1.1 MacOS Sonoma 

### ISSUE THREAD

**Issue by jp78fr** [molovol/MoloVol#139]
Hi all,
I have a MacBook Air Intel 2020 running Sonoma 14.2.1. The installation is from the dmg file. Version 1.1.0 works perfectly, whereas for version 1.1.1 I get the following error when I want to use Molovol:
"You can’t open the application “MoloVol” because this application is not supported on this Mac."

Have you ever encountered this problem and is there a solution?
Thank you very much.
Jean-Pierre

**Comment by jmaglic** [comment]
Hi Jean,

I will update my Mac to Sonoma and try to resolve your issue. Thanks for reaching out!

**Comment by jmaglic** [comment]
I have recompiled the app on Sonoma and it seems to work now. You can try the new installation file [here](https://github.com/molovol/MoloVol/releases/download/v1.1.1/MoloVol_macOS-10.11+_v1.1.1.dmg). Please just let me know whether it works for you.

**Comment by jp78fr** [comment]
I apologize for the late reply. Everything works perfectly with the recompiled version. Thank you very much.
