### ISSUE TITLE
Compile in Xcode fails

### ISSUE THREAD

**Issue by BSVogler** [molovol/MoloVol#45]
Since recent changes regarding the file system the compilation in xcode fails.
Compile with Xcode using the target cltool. The xcode setup uses the clang compiler with c++17 flags.

The error message
> Undefined symbols for architecture x86_64:
>   "fileExtension(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
>       MainFrame::enableGuiElements(bool) in base_event.o
>       Model::readAtomsFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool) in model_filereading.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by jmaglic** [comment]
This is likely related to commit e022b0e. The `fileExtension()` function was moved to `misc.cpp`, and `misc.h` was split into header and cpp file. Have you tried a complete recompilation?

**Comment by BSVogler** [comment]
I fixed it in the PR #44. The new file was not added to the included files.

**Comment by jmaglic** [comment]
Since we're now migrating to a CMake-based solution for building targets, I have modified the current CMakeLists.txt to provide more robust support for Xcode. An Xcode project file can be generated using CMake when creating the build files using `-GXcode`.

```console
 $ mkdir build-xc
 $ cd build-xc
 $ cmake .. -GXcode
```
